'use client'
import { useState, type FormEvent } from 'react'
import Link from 'next/link'
import { ArrowLeft, Blocks, Building2, KeyRound, Save } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { toast } from 'sonner'
import { dateLabel, moduleEnabled, moduleNames, planIncludes, type ModuleGrant, type Store } from '../lib/contracts'
import { useWorkspace } from './master-shell'
import { ApiKeyCell, storeAction } from './api-key-cell'
import { selectClass, StoreStatus } from './store-list'
import { AuditTable, InvoiceTable } from './tables'

function StoreEdit({ store }: { store: Store }) {
  const { refresh } = useWorkspace(), [open, setOpen] = useState(false), [pending, setPending] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true)
    try { await storeAction(store.id, { action: 'store.update', revision: store.revision, status: form.get('status') as Store['status'], plan: form.get('plan') as Store['plan'], reason: String(form.get('reason')) }); setOpen(false); toast.success('Loja atualizada.'); await refresh() }
    catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível salvar.') } finally { setPending(false) }
  }
  return <><Button variant="outline" onClick={() => setOpen(true)}>Gerenciar loja</Button><Dialog open={open} onOpenChange={value => { if (!pending) setOpen(value) }}><DialogContent><DialogHeader><DialogTitle>Gerenciar {store.name}</DialogTitle><DialogDescription>Altere a situação operacional e o plano de acesso. A assinatura e as cobranças existentes permanecem independentes.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label htmlFor="store-status">Situação da loja</Label><select id="store-status" name="status" defaultValue={store.status} className={`${selectClass} w-full`}><option value="active">Ativa</option><option value="trial">Em teste</option><option value="suspended">Suspensa</option></select></div><div className="space-y-2"><Label htmlFor="store-plan">Plano de acesso</Label><select id="store-plan" name="plan" defaultValue={store.plan} className={`${selectClass} w-full`}><option value="starter">Starter</option><option value="pro">Pro</option></select></div></div><div className="space-y-2"><Label htmlFor="store-reason">Motivo da alteração</Label><Textarea id="store-reason" name="reason" placeholder="Descreva o motivo para o histórico da loja" minLength={5} maxLength={300} required /></div><DialogFooter><Button type="button" variant="outline" disabled={pending} onClick={() => setOpen(false)}>Cancelar</Button><Button disabled={pending}><Save />{pending ? 'Salvando…' : 'Salvar alterações'}</Button></DialogFooter></form></DialogContent></Dialog></>
}
function ModuleEditor({ store, grant, close }: { store: Store; grant: ModuleGrant; close: () => void }) {
  const { refresh } = useWorkspace(), [pending, setPending] = useState(false), [override, setOverride] = useState(grant.override)
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true)
    try {
      const rawDate = String(form.get('expiresAt') || '')
      await storeAction(store.id, { action: 'module.update', revision: store.revision, code: grant.code, override, expiresAt: override !== 'plan' && rawDate ? new Date(`${rawDate}T23:59:59-03:00`).toISOString() : null, reason: String(form.get('reason')) })
      toast.success('Liberação atualizada.'); close(); await refresh()
    } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível salvar.') } finally { setPending(false) }
  }
  return <Dialog open onOpenChange={value => { if (!value && !pending) close() }}><DialogContent><DialogHeader><DialogTitle>{moduleNames[grant.code]} · {store.name}</DialogTitle><DialogDescription>Defina uma exceção para esta loja. Ao vencer, o acesso volta à regra do plano.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="space-y-2"><Label htmlFor="module-rule">Regra de acesso</Label><select id="module-rule" className={`${selectClass} w-full`} value={override} onChange={event => setOverride(event.target.value as ModuleGrant['override'])}><option value="plan">Seguir o plano</option><option value="enabled">Liberar para esta loja</option><option value="disabled">Bloquear para esta loja</option></select></div>{override !== 'plan' && <div className="space-y-2"><Label htmlFor="module-expiry">Válido até (opcional)</Label><Input id="module-expiry" name="expiresAt" type="date" defaultValue={grant.expiresAt ? new Date(grant.expiresAt).toLocaleDateString('en-CA', { timeZone: 'America/Sao_Paulo' }) : ''} /><p className="text-xs text-muted-foreground">Vencimento às 23:59 de Brasília. Em branco: sem vencimento.</p></div>}<div className="space-y-2"><Label htmlFor="module-reason">Motivo da alteração</Label><Textarea id="module-reason" name="reason" required minLength={5} maxLength={300} /></div><DialogFooter><Button type="button" variant="outline" disabled={pending} onClick={close}>Cancelar</Button><Button disabled={pending}>{pending ? 'Salvando…' : 'Salvar liberação'}</Button></DialogFooter></form></DialogContent></Dialog>
}
export function StoreDetail({ store }: { store: Store }) {
  const { data, session } = useWorkspace(), [editing, setEditing] = useState<ModuleGrant | null>(null)
  const now = Date.parse(data.updatedAt), bills = data.invoices.filter(invoice => invoice.storeId === store.id)
  return <div className="space-y-6"><Button asChild variant="ghost" size="sm" className="-ml-2"><Link href="/lojas"><ArrowLeft />Todas as lojas</Link></Button><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold tracking-tight">{store.name}</h1><StoreStatus status={store.status} /></div><p className="mt-2 text-muted-foreground">{store.domain} · Loja #{store.id}</p></div>{session.permissions.includes('stores.write') && <StoreEdit store={store} />}</div>
    <Tabs defaultValue="summary"><div className="overflow-x-auto"><TabsList className="mb-4"><TabsTrigger value="summary">Resumo</TabsTrigger><TabsTrigger value="modules">Módulos</TabsTrigger><TabsTrigger value="integrations">Integrações</TabsTrigger>{session.permissions.includes('billing.read') && <TabsTrigger value="billing">Assinatura e cobranças</TabsTrigger>}{session.permissions.includes('audit.read') && <TabsTrigger value="history">Histórico</TabsTrigger>}</TabsList></div>
      <TabsContent value="summary"><div className="grid gap-6 md:grid-cols-2"><section className="rounded-xl border bg-card p-6"><h2 className="mb-5 flex items-center gap-2 font-semibold"><Building2 className="size-4" />Dados da loja</h2><dl className="grid grid-cols-[auto_1fr] gap-x-6 gap-y-4 text-sm"><dt className="text-muted-foreground">Responsável</dt><dd>{store.owner}</dd><dt className="text-muted-foreground">E-mail</dt><dd className="break-all">{store.email}</dd><dt className="text-muted-foreground">Domínio</dt><dd className="break-all">{store.domain}</dd><dt className="text-muted-foreground">Cadastro</dt><dd>{dateLabel(store.createdAt)}</dd></dl></section><section className="rounded-xl border bg-card p-6"><h2 className="mb-5 flex items-center gap-2 font-semibold"><Blocks className="size-4" />Acesso à plataforma</h2><dl className="grid grid-cols-[auto_1fr] gap-x-6 gap-y-4"><dt className="text-muted-foreground">Plano</dt><dd>{store.plan === 'pro' ? 'Pro' : 'Starter'}</dd><dt className="text-muted-foreground">Assinatura</dt><dd>{{ active: 'Ativa', trial: 'Em teste', cancelled: 'Cancelada' }[store.subscription]}</dd><dt className="text-muted-foreground">Módulos liberados</dt><dd>{store.modules.filter(grant => moduleEnabled(store, grant, now)).length} de {store.modules.length}</dd></dl></section></div></TabsContent>
      <TabsContent value="modules"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{store.modules.map(grant => { const enabled = moduleEnabled(store, grant, now), expired = grant.expiresAt && Date.parse(grant.expiresAt) <= now; return <section key={grant.code} className="space-y-4 rounded-xl border bg-card p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">{moduleNames[grant.code]}</h2><Badge variant={enabled ? 'emerald' : 'slate'}>{enabled ? 'Liberado' : 'Bloqueado'}</Badge></div><p className="text-sm text-muted-foreground">{expired ? 'Exceção vencida · seguindo o plano' : grant.override === 'plan' ? planIncludes(store.plan, grant.code) ? 'Incluído no plano' : 'Não incluído no plano' : grant.expiresAt ? `Exceção até ${dateLabel(grant.expiresAt)}` : 'Exceção sem vencimento'}</p>{session.permissions.includes('modules.write') && <Button variant="outline" size="sm" onClick={() => setEditing(grant)}>Gerenciar acesso</Button>}</section> })}</div>{editing && <ModuleEditor key={editing.code} store={store} grant={editing} close={() => setEditing(null)} />}</TabsContent>
      <TabsContent value="integrations"><section className="max-w-2xl rounded-xl border bg-card p-6"><h2 className="flex items-center gap-2 font-semibold"><KeyRound className="size-4" />Chave API da loja</h2><p className="mb-5 mt-2 text-sm text-muted-foreground">Use esta chave nas integrações autorizadas da loja. O acesso à chave é registrado no histórico.</p><ApiKeyCell store={store} /><p className="mt-4 text-xs text-muted-foreground">A chave revelada é ocultada após um minuto ou ao sair desta janela.</p></section></TabsContent>
      {session.permissions.includes('billing.read') && <TabsContent value="billing"><div className="mb-4 rounded-xl border bg-card p-5"><p className="font-medium">Assinatura {{ active: 'ativa', trial: 'em teste', cancelled: 'cancelada' }[store.subscription]}</p><p className="mt-1 text-sm text-muted-foreground">Confira os pagamentos no histórico abaixo. A situação da assinatura não comprova o pagamento de uma cobrança.</p></div><InvoiceTable invoices={bills} /></TabsContent>}
      {session.permissions.includes('audit.read') && <TabsContent value="history"><AuditTable rows={data.audit.filter(event => event.storeId === store.id)} /></TabsContent>}
    </Tabs>
  </div>
}
