'use client'
import Link from 'next/link'
import { Badge } from '@/components/ui/badge'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { dateLabel, money, type Workspace } from '../lib/contracts'
import { useWorkspace } from './master-shell'

export function InvoiceTable({ invoices }: { invoices: Workspace['invoices'] }) {
  const { data } = useWorkspace()
  return <div className="overflow-hidden rounded-xl border bg-card"><Table className="master-table"><TableHeader><TableRow><TableHead className="pl-5">Loja / cobrança</TableHead><TableHead>Vencimento</TableHead><TableHead>Pagamento</TableHead><TableHead>Situação</TableHead><TableHead className="pr-5 text-right">Valor</TableHead></TableRow></TableHeader><TableBody>{invoices.map(invoice => <TableRow key={invoice.id}><TableCell className="py-4 pl-5"><Link className="font-medium hover:underline" href={`/lojas/${invoice.storeId}`}>{data.stores.find(store => store.id === invoice.storeId)?.name ?? `Loja #${invoice.storeId}`}</Link><p className="mt-1 text-xs text-muted-foreground">{invoice.description} · {invoice.id}</p></TableCell><TableCell>{dateLabel(invoice.dueAt)}</TableCell><TableCell>{invoice.paidAt ? dateLabel(invoice.paidAt) : '—'}</TableCell><TableCell><Badge variant={{ paid: 'emerald' as const, pending: 'blue' as const, overdue: 'rose' as const, cancelled: 'slate' as const }[invoice.status]}>{{ paid: 'Paga', pending: 'Pendente', overdue: 'Vencida', cancelled: 'Cancelada' }[invoice.status]}</Badge></TableCell><TableCell className="pr-5 text-right font-medium tabular-nums">{money(invoice.amount)}</TableCell></TableRow>)}</TableBody></Table>{!invoices.length && <p className="p-10 text-center text-muted-foreground">Nenhuma cobrança para este período.</p>}</div>
}
const actions: Record<string, string> = { 'key.reveal': 'Chave API revelada', 'key.copy': 'Chave API disponibilizada para cópia', 'store.update': 'Loja atualizada', 'module.update': 'Liberação de módulo alterada' }
export function AuditTable({ rows }: { rows: Workspace['audit'] }) {
  return <div className="overflow-hidden rounded-xl border bg-card"><Table className="master-table"><TableHeader><TableRow><TableHead className="pl-5">Ação</TableHead><TableHead>Operador</TableHead><TableHead>Loja</TableHead><TableHead>Data</TableHead><TableHead>Motivo / alterações</TableHead></TableRow></TableHeader><TableBody>{rows.map(event => <TableRow key={event.id}><TableCell className="py-4 pl-5 font-medium">{actions[event.action] ?? event.action}</TableCell><TableCell>{event.actor}</TableCell><TableCell>{event.storeId ? <Link className="hover:underline" href={`/lojas/${event.storeId}`}>#{event.storeId}</Link> : 'Plataforma'}</TableCell><TableCell className="whitespace-nowrap">{dateLabel(event.createdAt)}<p className="text-xs text-muted-foreground">{new Date(event.createdAt).toLocaleTimeString('pt-BR', { timeZone: 'America/Sao_Paulo' })}</p></TableCell><TableCell className="max-w-sm whitespace-normal"><p>{event.reason}</p>{event.before !== null && <details className="mt-2 text-xs text-muted-foreground"><summary className="cursor-pointer">Ver alteração</summary><p className="mt-2 break-all">Antes: {event.before}</p><p className="break-all">Depois: {event.after}</p></details>}</TableCell></TableRow>)}</TableBody></Table>{!rows.length && <p className="p-10 text-center text-muted-foreground">Nenhuma ação registrada. Alterações e acessos às chaves aparecerão aqui.</p>}</div>
}
