'use client'
import { useState } from 'react'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { SalesDashboard } from './sales-dashboard'
import Link from 'next/link'
import { ArrowRight, Store, CreditCard, CircleAlert, CircleCheck, Blocks, Clock3, ShieldCheck, Search } from 'lucide-react'
import { KpiCard } from '@/components/dashboard/shared'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useWorkspace } from './master-shell'
import { StoreList, StoreStatus, selectClass } from './store-list'
import { StoreDetail } from './store-detail'
import { AuditTable, InvoiceTable } from './tables'
import { dateLabel, moduleCodes, moduleEnabled, moduleNames, money, planIncludes, type Permission } from '../lib/contracts'

const titles: Record<string, [string, string]> = {
  '': ['Visão geral', 'Acompanhe a movimentação consolidada das marcas e seus clientes.'],
  clientes: ['Clientes', 'Faturamento, pedidos e relacionamento dos clientes de todas as marcas.'],
  lojas: ['Lojas', 'Gerencie os acessos e as integrações de cada loja.'],
  modulos: ['Planos e módulos', 'Consulte os recursos de cada plano e as liberações por loja.'],
  financeiro: ['Financeiro', 'Acompanhe as cobranças da plataforma por vencimento.'],
  relatorios: ['Relatórios', 'Recebimentos, planos e adoção dos módulos.'],
  equipe: ['Equipe e permissões', 'Consulte quem tem acesso à administração da plataforma.'],
  historico: ['Histórico de ações', 'Alterações e acessos registrados pela equipe.'],
}
const needed: Record<string, Permission> = { clientes: 'sales.read', financeiro: 'billing.read', relatorios: 'billing.read', equipe: 'team.read', historico: 'audit.read' }
const monthOf = (value: string) => new Intl.DateTimeFormat('sv-SE', { timeZone: 'America/Sao_Paulo', year: 'numeric', month: '2-digit' }).format(new Date(value))
function StoreMetrics() {
  const { data } = useWorkspace()
  return <div className="grid grid-cols-2 gap-3 md:gap-4 xl:grid-cols-4"><KpiCard title="Total de lojas" value={String(data.stores.length)} icon={<Store className="size-4" />} sub="Cadastradas na plataforma" /><KpiCard title="Lojas ativas" value={String(data.stores.filter(store => store.status === 'active').length)} icon={<CircleCheck className="size-4" />} sub="Situação operacional ativa" /><KpiCard title="Em teste" value={String(data.stores.filter(store => store.status === 'trial').length)} icon={<Clock3 className="size-4" />} sub="Acompanhamento de implantação" /><KpiCard title="Suspensas" value={String(data.stores.filter(store => store.status === 'suspended').length)} icon={<CircleAlert className="size-4" />} sub="Aguardando regularização" /></div>
}
function Overview({ month }: { month: string }) {
  const { data, session } = useWorkspace(), canBill = session.permissions.includes('billing.read')
  const paid = data.invoices.filter(item => item.status === 'paid' && item.paidAt && monthOf(item.paidAt) === month)
  const overdue = data.invoices.filter(item => item.status === 'overdue')
  return <div className="space-y-6"><StoreMetrics />{canBill && <div className="grid gap-4 md:grid-cols-3"><KpiCard title="Recebido no mês" value={money(paid.reduce((sum, item) => sum + item.amount, 0))} icon={<CreditCard className="size-4" />} sub={`${paid.length} cobranças pagas · por data de pagamento`} /><KpiCard title="Total vencido" value={money(overdue.reduce((sum, item) => sum + item.amount, 0))} icon={<CircleAlert className="size-4" />} sub={`${overdue.length} cobranças em aberto · todos os períodos`} /><KpiCard title="Assinaturas ativas" value={String(data.stores.filter(store => store.subscription === 'active').length)} icon={<Blocks className="size-4" />} sub="Recorrências configuradas atualmente" /></div>}
    <div className="grid items-start gap-6 xl:grid-cols-[1.6fr_1fr]"><section className="overflow-hidden rounded-xl border bg-card"><div className="flex items-center justify-between border-b p-5"><h2 className="font-semibold">Lojas recentes</h2><Button asChild variant="ghost" size="sm"><Link href="/lojas">Ver todas<ArrowRight /></Link></Button></div><Table><TableHeader><TableRow><TableHead className="pl-5">Loja</TableHead><TableHead>Plano</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{[...data.stores].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 5).map(store => <TableRow key={store.id}><TableCell className="py-4 pl-5"><Link className="font-medium hover:underline" href={`/lojas/${store.id}`}>{store.name}</Link><p className="mt-1 text-xs text-muted-foreground">Criada em {dateLabel(store.createdAt)}</p></TableCell><TableCell>{store.plan === 'pro' ? 'Pro' : 'Starter'}</TableCell><TableCell><StoreStatus status={store.status} /></TableCell></TableRow>)}</TableBody></Table>{!data.stores.length && <p className="p-8 text-muted-foreground">Nenhuma loja cadastrada.</p>}</section><section className="rounded-xl border bg-card p-5"><h2 className="mb-1 font-semibold">Acompanhamento</h2><p className="mb-5 text-xs text-muted-foreground">Lojas que precisam de atenção da equipe</p><div className="space-y-3">{data.stores.filter(store => store.status !== 'active').map(store => <Link key={store.id} href={`/lojas/${store.id}`} className="flex items-center gap-3 rounded-lg border p-3 hover:bg-muted/40"><div className="rounded-lg bg-muted p-2"><Store className="size-4 text-muted-foreground" /></div><div className="min-w-0 flex-1"><p className="truncate font-medium">{store.name}</p><p className="mt-1 text-xs text-muted-foreground">{store.status === 'trial' ? 'Acompanhar período de teste' : 'Revisar situação da loja'}</p></div><ArrowRight className="size-4 text-muted-foreground" /></Link>)}{data.stores.every(store => store.status === 'active') && <p className="py-4 text-muted-foreground">Nenhuma loja em teste ou suspensa.</p>}</div></section></div>
  </div>
}
function Finance({ month }: { month: string }) {
  const { data } = useWorkspace(), [status, setStatus] = useState('all')
  const invoices = data.invoices.filter(item => monthOf(item.dueAt) === month)
  return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-3">{(['paid', 'pending', 'overdue'] as const).map(state => <KpiCard key={state} title={{ paid: 'Pagas', pending: 'Pendentes', overdue: 'Vencidas' }[state]} value={money(invoices.filter(item => item.status === state).reduce((sum, item) => sum + item.amount, 0))} sub="Cobranças com vencimento no mês selecionado" />)}</div><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{invoices.length} cobranças no período</p><select aria-label="Filtrar cobranças" value={status} onChange={event => setStatus(event.target.value)} className={selectClass}><option value="all">Todas as situações</option><option value="paid">Pagas</option><option value="pending">Pendentes</option><option value="overdue">Vencidas</option><option value="cancelled">Canceladas</option></select></div><InvoiceTable invoices={invoices.filter(item => status === 'all' || item.status === status)} /></div>
}
function Modules() {
  const { data } = useWorkspace()
  return <div className="space-y-6"><div className="grid gap-5 md:grid-cols-2">{(['starter', 'pro'] as const).map(plan => <section className="rounded-xl border bg-card p-6" key={plan}><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{plan === 'pro' ? 'Pro' : 'Starter'}</h2><Badge variant={plan === 'pro' ? 'violet' : 'outline'}>{data.stores.filter(store => store.plan === plan).length} lojas</Badge></div><p className="mb-5 mt-2 text-muted-foreground">Módulos incluídos no plano de acesso</p><div className="flex flex-wrap gap-2">{moduleCodes.filter(code => planIncludes(plan, code)).map(code => <Badge variant="secondary" key={code}>{moduleNames[code]}</Badge>)}</div></section>)}</div><section className="overflow-hidden rounded-xl border bg-card"><div className="border-b p-5"><h2 className="font-semibold">Liberações por loja</h2><p className="mt-1 text-sm text-muted-foreground">Abra a loja para configurar exceções ou acessos temporários.</p></div><Table className="master-table"><TableHeader><TableRow><TableHead className="pl-5">Loja</TableHead>{moduleCodes.map(code => <TableHead key={code}>{moduleNames[code]}</TableHead>)}</TableRow></TableHeader><TableBody>{data.stores.map(store => <TableRow key={store.id}><TableCell className="py-4 pl-5"><Link href={`/lojas/${store.id}`} className="font-medium hover:underline">{store.name}</Link></TableCell>{moduleCodes.map(code => { const grant = store.modules.find(item => item.code === code); const enabled = grant && moduleEnabled(store, grant, Date.parse(data.updatedAt)); return <TableCell key={code}><Badge variant={enabled ? 'emerald' : 'secondary'}>{enabled ? 'Liberado' : 'Bloqueado'}</Badge></TableCell> })}</TableRow>)}</TableBody></Table>{!data.stores.length && <p className="p-8 text-muted-foreground">Nenhuma loja cadastrada.</p>}</section></div>
}
function Reports({ month }: { month: string }) {
  const { data } = useWorkspace()
  const paid = data.invoices.filter(item => item.status === 'paid' && item.paidAt && monthOf(item.paidAt) === month)
  return <div className="grid items-start gap-6 xl:grid-cols-2"><section className="rounded-xl border bg-card p-6"><h2 className="font-semibold">Recebimentos por plano</h2><p className="mb-6 mt-1 text-sm text-muted-foreground">Pagamentos no mês · agrupados pelo plano atual da loja</p>{(['starter', 'pro'] as const).map(plan => { const stores = data.stores.filter(store => store.plan === plan); const total = paid.filter(item => stores.some(store => store.id === item.storeId)).reduce((sum, item) => sum + item.amount, 0); return <div key={plan} className="flex justify-between border-b py-4 last:border-0"><div><p className="font-medium">{plan === 'pro' ? 'Pro' : 'Starter'}</p><p className="mt-1 text-xs text-muted-foreground">{stores.length} lojas no plano atualmente</p></div><p className="text-lg font-semibold tabular-nums">{money(total)}</p></div>})}<p className="mt-5 text-xs text-muted-foreground">Valores de cobranças da UP Zero. A movimentação dos pedidos das marcas está disponível na Visão geral.</p></section><section className="rounded-xl border bg-card p-6"><h2 className="font-semibold">Adoção de módulos</h2><p className="mb-6 mt-1 text-sm text-muted-foreground">Lojas com acesso liberado atualmente</p><div className="space-y-5">{moduleCodes.map(code => { const count = data.stores.filter(store => store.modules.some(grant => grant.code === code && moduleEnabled(store, grant, Date.parse(data.updatedAt)))).length; return <div key={code}><div className="mb-2 flex justify-between text-sm"><span>{moduleNames[code]}</span><span className="font-medium tabular-nums">{count} de {data.stores.length}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${data.stores.length ? count / data.stores.length * 100 : 0}%` }} /></div></div>})}</div></section></div>
}
function Team() {
  const { data } = useWorkspace()
  return <div className="space-y-4">{data.team.map(member => <section key={member.id} className="rounded-xl border bg-card p-6"><div className="flex items-start gap-4"><div className="rounded-full bg-muted p-3"><ShieldCheck className="size-5" /></div><div><h2 className="font-semibold">{member.name}</h2><p className="mt-1 text-muted-foreground">{member.email}</p><Badge variant="outline" className="mt-3">{member.role}</Badge></div></div><div className="mt-5 flex flex-wrap gap-2">{member.permissions.map(permission => <Badge variant="secondary" key={permission}>{{ 'stores.read': 'Consultar lojas', 'stores.write': 'Gerenciar lojas', 'keys.read': 'Visualizar chaves API', 'modules.write': 'Gerenciar módulos', 'billing.read': 'Consultar financeiro', 'audit.read': 'Consultar histórico', 'team.read': 'Consultar equipe', 'sales.read': 'Consultar clientes e movimentação' }[permission]}</Badge>)}</div></section>)}{!data.team.length && <p className="rounded-xl border bg-card p-8 text-muted-foreground">Nenhum usuário disponível para consulta.</p>}</div>
}
function HistoryView() {
  const { data, refresh } = useWorkspace(), [query, setQuery] = useState('')
  return <div className="space-y-4"><div className="flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" aria-label="Buscar histórico" placeholder="Buscar por operador, loja ou motivo…" value={query} onChange={event => setQuery(event.target.value)} /></div><Button variant="outline" onClick={() => void refresh()}>Atualizar histórico</Button></div><AuditTable rows={data.audit.filter(item => `${item.actor} ${item.storeId ?? ''} ${item.reason} ${item.action}`.toLowerCase().includes(query.toLowerCase()))} /></div>
}
export function WorkspaceView({ section, storeId }: { section: string; storeId?: number }) {
  const { data, session } = useWorkspace(), [month, setMonth] = useState(() => monthOf(data.updatedAt))
  if (needed[section] && !session.permissions.includes(needed[section])) return <div role="alert" className="rounded-xl border bg-card p-8"><h1 className="text-xl font-semibold">Acesso restrito</h1><p className="mt-2 text-muted-foreground">Seu perfil não permite consultar esta área.</p></div>
  if (storeId) { const store = data.stores.find(item => item.id === storeId); return store ? <StoreDetail key={store.id} store={store} /> : <div className="space-y-4"><h1 className="text-xl font-semibold">Loja não encontrada</h1><Button asChild><Link href="/lojas">Voltar às lojas</Link></Button></div> }
  const [title, subtitle] = titles[section]
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{subtitle}</p></div>{['financeiro', 'relatorios'].includes(section) && session.permissions.includes('billing.read') && <label className="space-y-1 text-xs text-muted-foreground"><span className="block">Período financeiro</span><Input aria-label="Período financeiro" type="month" className="w-auto bg-card" value={month} onChange={event => { if (event.target.value) setMonth(event.target.value) }} /></label>}</div>
    {section === '' && (session.permissions.includes('sales.read') ? <Tabs defaultValue="sales"><TabsList className="mb-3"><TabsTrigger value="sales">Movimentação das marcas</TabsTrigger><TabsTrigger value="platform">Operação da plataforma</TabsTrigger></TabsList><TabsContent value="sales"><SalesDashboard /></TabsContent><TabsContent value="platform"><div className="mb-4 flex justify-end"><Input aria-label="Período financeiro da plataforma" type="month" className="w-auto" value={month} onChange={event => { if (event.target.value) setMonth(event.target.value) }} /></div><Overview month={month} /></TabsContent></Tabs> : <Overview month={month} />)}{section === 'clientes' && <SalesDashboard customersOnly />}{section === 'lojas' && <><StoreMetrics /><StoreList /></>}{section === 'modulos' && <Modules />}{section === 'financeiro' && <Finance month={month} />}{section === 'relatorios' && <Reports month={month} />}{section === 'equipe' && <Team />}{section === 'historico' && <HistoryView />}
    <p className="pt-2 text-xs text-muted-foreground">{session.mode === 'demo' ? 'Ambiente de demonstração · ' : ''}Última atualização: {dateLabel(data.updatedAt)} às {new Date(data.updatedAt).toLocaleTimeString('pt-BR', { timeZone: 'America/Sao_Paulo', hour: '2-digit', minute: '2-digit' })} · Horário de Brasília</p>
  </div>
}
