import type {
  Branch,
  Customer,
  MessageFlow,
  MessageTemplate,
  Order,
  PriceTable,
  Product,
  WhatsAppConfig,
} from "@/lib/types"

const now = new Date("2026-04-07T10:00:00-03:00")

export const adminMockCustomers: Customer[] = [
  {
    id: "cust-mock-1",
    userId: "user-mock-1",
    customerType: "WHOLESALE",
    companyName: "Atelie Aurora Ltda",
    tradeName: "Aurora Concept",
    cnpj: "12345678000199",
    stateRegistration: "123456789",
    contactName: "Marina Oliveira",
    phone: "11987654321",
    email: "marina@auroraconcept.com.br",
    street: "Rua das Palmeiras",
    number: "245",
    complement: "Sala 4",
    neighborhood: "Jardins",
    city: "Sao Paulo",
    state: "SP",
    zipCode: "01414001",
    segment: "Moda feminina",
    status: "APPROVED",
    priceTableId: "price-mock-1",
    minPiecesOverride: null,
    extraDiscountPct: 3,
    paymentTerms: ["PIX", "BOLETO"],
    assignedSellerId: "seller-1",
    assignedSellerName: "Ana Souza",
    createdAt: new Date("2026-03-11T14:15:00-03:00"),
    updatedAt: now,
  },
  {
    id: "cust-mock-2",
    userId: "user-mock-2",
    customerType: "WHOLESALE",
    companyName: "Loja Brisa Tropical",
    tradeName: "Brisa Tropical",
    cnpj: "44222111000155",
    stateRegistration: null,
    contactName: "Paulo Mendes",
    phone: "21999887766",
    email: "compras@brisatropical.com",
    street: "Av. Atlantica",
    number: "88",
    complement: null,
    neighborhood: "Copacabana",
    city: "Rio de Janeiro",
    state: "RJ",
    zipCode: "22021001",
    segment: "Resortwear",
    status: "PENDING",
    priceTableId: "price-mock-2",
    minPiecesOverride: null,
    extraDiscountPct: null,
    paymentTerms: ["PIX"],
    assignedSellerId: null,
    createdAt: new Date("2026-04-03T09:00:00-03:00"),
    updatedAt: now,
  },
  {
    id: "cust-mock-3",
    userId: "user-mock-3",
    customerType: "WHOLESALE",
    companyName: "Casa Nativa Fashion",
    tradeName: "Casa Nativa",
    cnpj: "88777099000110",
    stateRegistration: "99887766",
    contactName: "Luciana Prado",
    phone: "31988776655",
    email: "luciana@casanativa.com",
    street: "Rua da Bahia",
    number: "1200",
    complement: "Loja 12",
    neighborhood: "Centro",
    city: "Belo Horizonte",
    state: "MG",
    zipCode: "30160011",
    segment: "Multimarcas",
    status: "APPROVED",
    priceTableId: "price-mock-1",
    minPiecesOverride: null,
    extraDiscountPct: 5,
    paymentTerms: ["PIX", "FATURADO"],
    assignedSellerId: "seller-2",
    assignedSellerName: "Renata Lima",
    createdAt: new Date("2026-02-20T16:40:00-03:00"),
    updatedAt: now,
  },
]

export const adminMockProducts: Product[] = [
  {
    id: "prod-mock-1",
    name: "Vestido Midi Serena",
    slug: "vestido-midi-serena",
    sku: "SER-4201",
    description: "Vestido midi com toque acetinado e caimento reto.",
    materials: "Viscose premium",
    measures: "36 ao 44",
    basePrice: 189.9,
    cost: 82.3,
    isActive: true,
    isFeatured: true,
    categoryId: "cat-1",
    categoryIds: ["cat-1"],
    tags: ["best-seller", "colecao-outono"],
    images: ["/placeholder.jpg"],
    sizes: ["P", "M", "G"],
    colors: [
      { id: "color-1", name: "Areia", hex: "#d8c3ab", images: ["/placeholder.jpg"] },
      { id: "color-2", name: "Cafe", hex: "#6b4e3d", images: ["/placeholder.jpg"] },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-mock-2",
    name: "Blazer Florenca",
    slug: "blazer-florenca",
    sku: "BLZ-2100",
    description: "Blazer estruturado com modelagem moderna.",
    materials: "Alfaiataria mista",
    measures: "P ao GG",
    basePrice: 249.9,
    cost: 121.5,
    isActive: true,
    isFeatured: false,
    categoryId: "cat-2",
    categoryIds: ["cat-2"],
    tags: ["alfaiataria"],
    images: ["/placeholder.jpg"],
    sizes: ["P", "M", "G", "GG"],
    colors: [{ id: "color-3", name: "Preto", hex: "#1c1c1c", images: ["/placeholder.jpg"] }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-mock-3",
    name: "Conjunto Riviera",
    slug: "conjunto-riviera",
    sku: "RIV-1180",
    description: "Conjunto leve para viagens e resortwear.",
    materials: "Linho misto",
    measures: "P ao G",
    basePrice: 279.9,
    cost: 140,
    isActive: false,
    isFeatured: false,
    categoryId: "cat-3",
    categoryIds: ["cat-3"],
    tags: ["resort"],
    images: ["/placeholder.jpg"],
    sizes: ["P", "M", "G"],
    colors: [{ id: "color-4", name: "Off White", hex: "#f3eee4", images: ["/placeholder.jpg"] }],
    createdAt: now,
    updatedAt: now,
  },
]

export const adminMockOrders: Order[] = [
  {
    id: "ordmock001",
    customerId: "cust-mock-1",
    createdByUserId: "seller-1",
    createdBySellerId: "seller-1",
    status: "PROCESSING",
    paymentStatus: "PAID",
    subtotal: 379.8,
    couponDiscount: 0,
    tierDiscount: 18.99,
    discountTotal: 18.99,
    manualDiscount: 0,
    total: 390.81,
    fulfilledTotal: 189.9,
    totalItems: 6,
    fulfilledItems: 3,
    shippingName: "Transportadora Sul",
    shippingPrice: 30,
    paymentMethod: "PIX",
    notes: "Separar cabides premium",
    internalNotes: "Cliente VIP",
    trackingCode: "BR123456789",
    trackingUrl: "https://example.com/tracking/BR123456789",
    shippingStreet: "Rua das Palmeiras",
    shippingNumber: "245",
    shippingComplement: "Sala 4",
    shippingNeighborhood: "Jardins",
    shippingCity: "Sao Paulo",
    shippingState: "SP",
    shippingZipCode: "01414001",
    createdAt: new Date("2026-04-06T08:20:00-03:00"),
    updatedAt: now,
  },
  {
    id: "ordmock002",
    customerId: "cust-mock-2",
    createdByUserId: "seller-2",
    createdBySellerId: "seller-2",
    status: "PENDING",
    paymentStatus: "PENDING",
    subtotal: 249.9,
    couponDiscount: 0,
    tierDiscount: 0,
    discountTotal: 0,
    manualDiscount: 0,
    total: 274.9,
    fulfilledTotal: 0,
    totalItems: 4,
    fulfilledItems: 0,
    shippingName: "Entrega Expressa",
    shippingPrice: 25,
    paymentMethod: "BOLETO",
    notes: null,
    internalNotes: null,
    trackingCode: null,
    trackingUrl: null,
    shippingStreet: "Av. Atlantica",
    shippingNumber: "88",
    shippingComplement: null,
    shippingNeighborhood: "Copacabana",
    shippingCity: "Rio de Janeiro",
    shippingState: "RJ",
    shippingZipCode: "22021001",
    createdAt: new Date("2026-04-05T17:45:00-03:00"),
    updatedAt: now,
  },
  {
    id: "ordmock003",
    customerId: "cust-mock-3",
    createdByUserId: "seller-2",
    createdBySellerId: "seller-2",
    status: "DELIVERED",
    paymentStatus: "PAID",
    subtotal: 559.8,
    couponDiscount: 50,
    tierDiscount: 27.99,
    discountTotal: 77.99,
    manualDiscount: 0,
    total: 501.81,
    fulfilledTotal: 501.81,
    totalItems: 8,
    fulfilledItems: 8,
    shippingName: "Loggi",
    shippingPrice: 20,
    paymentMethod: "PIX",
    notes: "Enviar nova tabela na proxima compra",
    internalNotes: "Pos-venda excelente",
    trackingCode: "LG99887766",
    trackingUrl: "https://example.com/tracking/LG99887766",
    shippingStreet: "Rua da Bahia",
    shippingNumber: "1200",
    shippingComplement: "Loja 12",
    shippingNeighborhood: "Centro",
    shippingCity: "Belo Horizonte",
    shippingState: "MG",
    shippingZipCode: "30160011",
    createdAt: new Date("2026-03-30T11:10:00-03:00"),
    updatedAt: now,
  },
]

export const adminMockPriceTables: PriceTable[] = [
  {
    id: "price-mock-1",
    name: "Atacado Premium",
    type: "PERCENTAGE",
    percentage: 12,
    isDefault: true,
    isActive: true,
    createdAt: now,
  },
  {
    id: "price-mock-2",
    name: "Entrada Novos Clientes",
    type: "PERCENTAGE",
    percentage: 5,
    isDefault: false,
    isActive: true,
    createdAt: now,
  },
]

export const adminMockMessaging = {
  whatsappConfig: {
    isEnabled: true,
    provider: "META_CLOUD",
    phoneNumberId: "109876543210",
    accessToken: "mock-access-token",
    businessAccountId: "9988776655",
    webhookVerifyToken: "admin-mobile-demo",
    isConnected: true,
    connectedAt: now,
  } satisfies WhatsAppConfig,
  templates: [
    {
      id: "tmpl-mock-1",
      name: "Boas-vindas WhatsApp",
      trigger: "CUSTOMER_APPROVED",
      isActive: true,
      channel: "WHATSAPP",
      content: "Oi {{nome}}, seu cadastro foi aprovado. Seu atendimento agora segue com {{vendedora}}.",
      variables: ["{{nome}}", "{{vendedora}}"],
      delayMinutes: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tmpl-mock-2",
      name: "Pedido em separacao",
      trigger: "ORDER_PROCESSING",
      isActive: true,
      channel: "WHATSAPP",
      content: "Pedido {{pedido}} em separacao. Total confirmado: {{valor}}.",
      variables: ["{{pedido}}", "{{valor}}"],
      delayMinutes: 0,
      createdAt: now,
      updatedAt: now,
    },
  ] satisfies MessageTemplate[],
  flows: [
    {
      id: "flow-mock-1",
      name: "Reengajamento de carrinho",
      description: "Aciona WhatsApp e follow-up de vendedora em ate 2 horas.",
      trigger: "CART_ABANDONED",
      isActive: true,
      steps: [
        {
          id: "step-1",
          name: "Lembrete inicial",
          conditions: [],
          conditionLogic: "AND",
          actions: [
            {
              id: "action-1",
              type: "SEND_WHATSAPP",
              config: {
                message: "Oi {{nome}}, deixamos sua selecao salva aqui: {{link}}",
              },
            },
          ],
          nextStepId: "step-2",
        },
        {
          id: "step-2",
          name: "Escalonar para vendedora",
          conditions: [
            {
              id: "condition-1",
              type: "TIME_DELAY",
              operator: "GREATER_THAN",
              value: 120,
            },
          ],
          conditionLogic: "AND",
          actions: [
            {
              id: "action-2",
              type: "ASSIGN_SELLER",
              config: {},
            },
          ],
          nextStepId: null,
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
  ] satisfies MessageFlow[],
}

export const adminMockBranches: Branch[] = [
  {
    id: "branch-mock-1",
    storeId: 1,
    name: "São Paulo",
    slug: "saopaulo",
    status: "active",
    isDefault: true,
    city: "São Paulo",
    state: "SP",
    description: "Filial principal — atende revendedores da Grande São Paulo e interior.",
    responsibleName: "Ana Souza",
    contactWhatsapp: "+55 11 98765-4321",
    contactEmail: "sp@marca.com.br",
    themeConfig: null,
    seoConfig: null,
    trackingConfig: null,
    catalogConfig: null,
    pricingTableId: null,
    salesChannelCode: null,
    createdAt: new Date("2026-01-10T09:00:00-03:00"),
    updatedAt: now,
    deletedAt: null,
  },
  {
    id: "branch-mock-2",
    storeId: 1,
    name: "Rio de Janeiro",
    slug: "riodejaneiro",
    status: "active",
    isDefault: false,
    city: "Rio de Janeiro",
    state: "RJ",
    description: "Atende lojistas do Rio de Janeiro e região serrana.",
    responsibleName: "Renata Lima",
    contactWhatsapp: "+55 21 99887-6655",
    contactEmail: "rj@marca.com.br",
    themeConfig: null,
    seoConfig: null,
    trackingConfig: null,
    catalogConfig: null,
    pricingTableId: null,
    salesChannelCode: null,
    createdAt: new Date("2026-01-15T11:30:00-03:00"),
    updatedAt: now,
    deletedAt: null,
  },
  {
    id: "branch-mock-3",
    storeId: 1,
    name: "Curitiba",
    slug: "curitiba",
    status: "active",
    isDefault: false,
    city: "Curitiba",
    state: "PR",
    description: "Filial Sul — cobre Paraná, Santa Catarina e Rio Grande do Sul.",
    responsibleName: "Carlos Mendes",
    contactWhatsapp: "+55 41 99111-2233",
    contactEmail: "sul@marca.com.br",
    themeConfig: null,
    seoConfig: null,
    trackingConfig: null,
    catalogConfig: null,
    pricingTableId: null,
    salesChannelCode: null,
    createdAt: new Date("2026-02-01T08:00:00-03:00"),
    updatedAt: now,
    deletedAt: null,
  },
  {
    id: "branch-mock-4",
    storeId: 1,
    name: "Nordeste",
    slug: "nordeste",
    status: "inactive",
    isDefault: false,
    city: "Fortaleza",
    state: "CE",
    description: "Em implementação — previsto para Q3 2026.",
    responsibleName: null,
    contactWhatsapp: null,
    contactEmail: null,
    themeConfig: null,
    seoConfig: null,
    trackingConfig: null,
    catalogConfig: null,
    pricingTableId: null,
    salesChannelCode: null,
    createdAt: new Date("2026-03-20T14:00:00-03:00"),
    updatedAt: now,
    deletedAt: null,
  },
]

export function withAdminMockBranches(branches: Branch[]) {
  return branches.length > 0 ? branches : adminMockBranches
}

export function withAdminMockOrders(orders: Order[]) {
  return orders.length > 0 ? orders : adminMockOrders
}

export function withAdminMockCustomers(customers: Customer[]) {
  return customers.length > 0 ? customers : adminMockCustomers
}

export function withAdminMockProducts(products: Product[]) {
  return products.length > 0 ? products : adminMockProducts
}

export function withAdminMockMessaging<Data extends { templates: MessageTemplate[]; flows: MessageFlow[] } | undefined>(
  data: Data,
) {
  if (data && data.templates.length > 0 && data.flows.length > 0) {
    return data
  }
  return adminMockMessaging
}
